### ISSUE TITLE
'Kill history' command non-functional

### ISSUE THREAD

**Issue by ijoseph** [dvkt/vscode-kill-ring#15]
# Reproduce
1. Kill two or more lines with <kbd>⌘ </kbd><kbd>k</kbd>.
2. Open command palette
<img width="379" alt="image" src="https://user-images.githubusercontent.com/549191/236380454-1ede8d27-7cc0-4350-9ed6-05884f4787f2.png">
3. Select 'Kill history' and press enter

## Expected result
Kill-history pane pops up
![image](https://user-images.githubusercontent.com/549191/236380396-a83683c0-746b-4bce-988d-61e28cc20e60.png)

## Actual result
Nothing appears to occur

# Environment 
```yaml
Version: 1.77.3 (Universal)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z (3 wks ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No 
```
